theme: minima
title: Backend Engineer
name: Trang Nguyen
url: https://trangnkp.github.io

author:
  name: Trang Nguyen
  email: ngkimphuongtrang@gmail.com
  location: Ho Chi Minh city, Vietnam
  employer: "Trusting Social"